<script lang="ts">
	import { onMount } from 'svelte';

	/**
	 * Registers the Workbox service worker generated by `@vite-pwa/sveltekit`.
	 *
	 * This component renders nothing — it exists so registration happens inside
	 * a Svelte lifecycle hook rather than via an injected inline script.
	 *
	 * Two details matter:
	 *
	 * 1. The virtual module is imported *dynamically inside `onMount`*, not at the
	 *    top level. SvelteKit prerenders this app, so a static import would be
	 *    resolved during the SSR/prerender pass, where the virtual module has no
	 *    meaning. Guarding it behind `import.meta.env.PROD` also keeps the dev
	 *    server free of a service worker that would cache localhost modules.
	 *
	 * 2. The service worker's own scope is resolved by the browser against this
	 *    document's URL, so the generated `/sw.js` is found correctly under a
	 *    GitHub Pages sub-path (`/<repo>/sw.js`) without hardcoding a base.
	 */
	onMount(() => {
		if (!import.meta.env.PROD) return;
		if (!('serviceWorker' in navigator)) return;

		import('virtual:pwa-register')
			.then(({ registerSW }) => {
				registerSW({
					// `registerType: 'autoUpdate'` in vite.config.ts means the
					// plugin reloads the page once a new worker takes over, so
					// these hooks are notification-only.
					onNeedRefresh() {
						/* update available — autoUpdate handles it */
					},
					onOfflineReady() {
						/* precache complete — app is now usable offline */
					},
					onRegisterError(error) {
						// Surfaced rather than swallowed: a service worker that
						// silently fails to install is very hard to diagnose,
						// and the app still works online either way.
						console.warn('[pwa] service worker registration failed', error);
					}
				});
			})
			.catch((error) => {
				// The virtual module is dev-only-stubbed; a rejected import here
				// means the registration chunk failed to load. The app remains
				// fully functional online, so this is a warning, not a crash.
				console.warn('[pwa] could not load the registration module', error);
			});
	});
</script>
